server:
  port: 8006
spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud20201203?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        hostname: 172.24.160.1
      host: 47.115.38.255
      port: 8500
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true
